
-- Run as the DB owner (pgUser in your script)
-- WARNING! DROPS AND RE-CREATES SCHEMA
-- DEPENDS ON: initdb.sql

DROP SCHEMA IF EXISTS cam_cms CASCADE;
CREATE SCHEMA cam_cms;

GRANT USAGE, CREATE ON SCHEMA cam_cms TO CURRENT_USER;

-- per-team apiuser
GRANT USAGE ON SCHEMA cam_cms TO :apiuser;

-- team group role
GRANT USAGE, CREATE ON SCHEMA cam_cms TO :teamrole;
GRANT :teamrole TO CURRENT_USER;

REVOKE ALL ON SCHEMA cam_cms FROM PUBLIC;

ALTER DEFAULT PRIVILEGES IN SCHEMA cam_cms
      GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO :apiuser;
ALTER DEFAULT PRIVILEGES IN SCHEMA cam_cms
      GRANT USAGE ON SEQUENCES TO :apiuser;

ALTER DEFAULT PRIVILEGES IN SCHEMA cam_cms
      GRANT SELECT,INSERT,UPDATE,DELETE ON TABLES TO :teamrole;
ALTER DEFAULT PRIVILEGES IN SCHEMA cam_cms
      GRANT USAGE ON SEQUENCES TO :teamrole;